### ISSUE TITLE
Unable to sort coins in portfolio

### ISSUE THREAD

**Issue by mloeffen** [hodlerhacks/balance-bot-v2-staging#1]
When I open a dashboard and look at my portfolio, I cannot sort the coins. When I hover over a columnheader I see the mouse pointer turn into a hand, but clicking it doesn't change anything. There is nothing logged in the console. Tested with Edge 96.0.1054.57 and Firefox 95.0.1

**Comment by hodlerhacks** [comment]
This has been resolved in a recent update
